### ISSUE TITLE
Request for new movie sites 

### ISSUE THREAD

**Issue by Zafor7869** [redowan99/Redowan-CloudStream#20]
![Screenshot_20240924_191845](https://github.com/user-attachments/assets/eba9d44e-caad-432a-a2f3-3a10b1d5a468)

https://cinefreak.net/
https://fullymaza.pw/

Bhi ei website gula ki add korte parben apnar playliste. Jodi free thaken ektu dekhe niyen add kora jai kina.

**Comment by salman731** [comment]
I will look into this
