### ISSUE TITLE
Site Request

### ISSUE THREAD

**Issue by Politecoder** [redowan99/Redowan-CloudStream#22]
https://hdhub4u.futbol/
Please add this site it has everything and has good server

**Comment by salman731** [comment]
I will look into this

**Comment by Politecoder** [comment]
Thanks bro

**Comment by redowan99** [comment]
Working on it.

**Comment by salman731** [comment]
This site have protected links is there way to bypass it ?

**Comment by redowan99** [comment]
Hdhub4u has another domain which doesn't have protection. I will work on that one. But they might update their website in the future.

**Comment by Politecoder** [comment]
Thanks brother for adding it

**Comment by redowan99** [comment]
Need to fix few things, but currently working somewhat.
