### ISSUE TITLE
Fix Fibwatch Website 

### ISSUE THREAD

**Issue by Zafor7869** [redowan99/Redowan-CloudStream#25]
![Screenshot_20241005_005924](https://github.com/user-attachments/assets/3e1d5d9c-cec9-4e57-b489-6deb00b1b34d)

https://fibwatch.online/

Bhi ei website ta kaj kortese na apnar extensiona free hole ektu thik kore diyen.

**Comment by redowan99** [comment]
Added Cloudflare. Fibwatch will be disabled from now.
