### ISSUE TITLE
Skymovies issue

### ISSUE THREAD

**Issue by AsfandYar1211** [redowan99/Redowan-CloudStream#3]
https://skymovieshd.chat/movie/One-Piece-(2023)-720p-HEVC-HDRip-S01-Complete-NF-Series-[Dual-Audio]-[Hindi-or-English]-x265-MSubs-[1.2GB].html

There's this issue in skymovies site series like its just scraping the links of 1st four episodes.. ignoring next four and 1080p links.. Same also works for other series...
And also  add scraper( if there's any) for sharer.pw(or some else) server as some old movies have just this server

**Comment by redowan99** [comment]
Working in this issue.

**Comment by AsfandYar1211** [comment]
https://skymovieshd.chat/movie/Vikings-(2014)-720p-HEVC-HDRip-S02-Complete-NF-Series-[Dual-Audio]-[Hindi-or-English]-x265-AAC-ESubs-[1.2GB].html

**Comment by redowan99** [comment]
Fixed This Issue
