### ISSUE TITLE
Request for Anime Websites

### ISSUE THREAD

**Issue by Zafor7869** [redowan99/Redowan-CloudStream#30]
![Screenshot_20241010_035058](https://github.com/user-attachments/assets/c0eff5aa-e891-4c68-ad00-2439ab45c6d0)
![Screenshot_20241010_035127](https://github.com/user-attachments/assets/f4e10fa5-4f7e-42fd-b423-59149e94a40d)

https://deadstream.xyz/home
https://coolsanime.world/

Bhi jodi free thaken ei 2ta anime site add kore diyen apnar extensiona. Eikhane multi language anime online stream kora jai onek source link available ase.

**Comment by salman731** [comment]
https://deadstream.xyz/home 
Already added to csx repo

**Comment by Zafor7869** [comment]
https://fibwatch.online/

Bhi ei website ta ekhon ar cloudflare dekhai na mone hoy ora remove kore dise jodi add kora jai taile kore diyen.

**Comment by redowan99** [comment]
I will add https://coolsanime.world/
