### ISSUE TITLE
Add movie sites 

### ISSUE THREAD

**Issue by aksa03** [redowan99/Redowan-CloudStream#34]
Please add these movie site
https://1cinevood.pics/
https://hdfriday.guru/

**Comment by yusufxz** [comment]
Can you find and add new full match viewing sites similar to the FullMatch site? Please Redovan

**Comment by rockhero1234** [comment]
I pushed cinevood to csx. Unable to scrap links in hdfriday

**Comment by redowan99** [comment]
> Can you find and add new full match viewing sites similar to the FullMatch site? Please Redovan

I currently don't know any, if you have some site let me know and please open a new issue.
