### ISSUE TITLE
Add Ssrmovies Website 

### ISSUE THREAD

**Issue by Zafor7869** [redowan99/Redowan-CloudStream#38]
![Screenshot_2024_1014_223940](https://github.com/user-attachments/assets/e8a95875-53b7-4692-96eb-d809c2e1f717)

https://ssrmovies.contact/

Bhi ei website ta parle add kore diyen jodi add kora jai. Eita onek ager ebon valo ekti site. Ami 5 theke 6 bosor jabot use kortese.

**Comment by redowan99** [comment]
This website will not be possible, there is encryption in file links.
