### ISSUE TITLE
Again requesting 

### ISSUE THREAD

**Issue by AsfandYar1211** [redowan99/Redowan-CloudStream#39]
Kindly Add some resources of them 
https://makkitv.com/
https://superurdu.com/
https://www.giveme5.co/
https://play.niazitv.pk/
https://turkceurdu.com/
https://play.qayadat.org/
https://www.urdubolo.pk/
https://kayifamily.com/ ( eng)
https://kayifamilytv.pk/

**Comment by yusufxz** [comment]
This repository is facing such problem redovan can you fix this?

![IMG_20241023_105535](https://github.com/user-attachments/assets/63d1d86f-d9b8-4f94-8bcd-da26b3af0f54)

**Comment by redowan99** [comment]
> This repository is facing such problem redovan can you fix this?
> 
> ![IMG_20241023_105535](https://private-user-images.githubusercontent.com/174906968/379160092-63d1d86f-d9b8-4f94-8bcd-da26b3af0f54.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5OTIzMTgsIm5iZiI6MTcyOTk5MjAxOCwicGF0aCI6Ii8xNzQ5MDY5NjgvMzc5MTYwMDkyLTYzZDFkODZmLWQ5YjgtNGY5NC04YmNkLWRhMjZiM2FmMGY1NC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyN1QwMTIwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03Y2NkMzc0NTRkZjE5NWE0M2Y0YjIxNWFlNjZhNmRlZDRlMWIxNWMyMzcxNmVlNzA0NWRhMjQ5NmE5MDcxZGQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-nBJ4TF2B1eaMDmRMb9LgR9nKt2OuckaCivHnI94DPo)

Fullmatch is working perfectly fine on my side, try with a VPN.

**Comment by yusufxz** [comment]
Şu siteyi eklemelisin Redovan

https://www.fullreplays.com/page/2/

**Comment by yusufxz** [comment]
you should add this site Redovan

https://www.fullreplays.com/

**Comment by salman731** [comment]
> Kindly Add some resources of them https://makkitv.com/ https://superurdu.com/ https://www.giveme5.co/ https://play.niazitv.pk/ https://turkceurdu.com/ https://play.qayadat.org/ https://www.urdubolo.pk/ https://kayifamily.com/ ( eng) https://kayifamilytv.pk/

I will look into this....

**Comment by yusufxz** [comment]
Thank you for the new additions Dear Redovan.
