### ISSUE TITLE
skymovieshd links are not working

### ISSUE THREAD

**Issue by salman731** [redowan99/Redowan-CloudStream#5]
![Capture111](https://github.com/user-attachments/assets/5ff96ca3-c227-45da-878c-fdf3cd96a142)

**There are many links but it says links not found on cloudstream**

**Comment by redowan99** [comment]
Scraper wasn't working properly because website got updated. Currently working with few bugs. will fix those tomorrow if i have time.

**Comment by redowan99** [comment]
Fixed this issue.
