### ISSUE TITLE
fullreplays problem

### ISSUE THREAD

**Issue by mo142001** [redowan99/Redowan-CloudStream#52]
There is a problem with fullreplays
In the sections of Spain, England and Italy, there is only the first half of the match
Please add links of the second half and links of doods and vidhidehub.

**Comment by mo142001** [comment]
@redowan99

**Comment by redowan99** [comment]
Can you share few match links that are in two parts?

**Comment by mo142001** [comment]
https://www.fullreplays.com/spain/laliga/real-madrid-vs-barcelona-26-oct-2024/
https://www.fullreplays.com/uefa/uefa-nations-league/netherlands-vs-hungary-16-nov-2024/
https://www.fullreplays.com/italy/serie-a/inter-vs-napoli-10-nov-2024/
please add doods links 
@redowan99

**Comment by redowan99** [comment]
fixed

**Comment by mo142001** [comment]
Nothing Has Changed, it still only shows the first half
@redowan99

**Comment by redowan99** [comment]
your plugin might not been updated yet, check again or send me a screenshot. You might also not have set it to auto-update plugins.

**Comment by mo142001** [comment]
Thank you very much 
It's working now
@redowan99
