### ISSUE TITLE
Circle FTP broken

### ISSUE THREAD

**Issue by LazyDevUserX** [redowan99/Redowan-CloudStream#55]
IDK if it's just me but circle ftp suddenly stopped. Ig they changed something in their backend cuz the website was down last night
[Note: The website is online but the extension is broken]

**Comment by redowan99** [comment]
Yes. It is same bere. I will fix it today.

**Comment by LazyDevUserX** [comment]
really appreciate it man. 
but something fishy is happening in the background circles sudden blackout and ftpbd stopped other isp from accessing their server at the same time

**Comment by redowan99** [comment]
CircleFtp fixed. Ftpbd also stopped working for me. Circleftp problem is nothing new. Their TLS certificate problem happens once a few months. Now they have stopped using https and using http.😕

**Comment by LazyDevUserX** [comment]
FTPBD stopped other ISPs form accessing their server, i asked a moderator when it will open again but didn't get any clear answer currently only Bnet can access ftpbd
