### ISSUE TITLE
Add this movie site

### ISSUE THREAD

**Issue by Zafor7869** [redowan99/Redowan-CloudStream#59]
https://extramovies.soy/

Brother, could you add this site in extension. If possible to add it. 

![Screenshot_20241206_213721](https://github.com/user-attachments/assets/aa33f474-3e26-4981-bc9f-0302ed6d4502)

**Comment by redowan99** [comment]
Site is good, but file hosting server they use, hubcloud doesn't support streaming, that's why it isn't suitable for Cloudstream.
